# Generated by Django 2.2.3 on 2020-04-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=255)),
                ('activity_date', models.CharField(max_length=255)),
                ('activity_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('department_id', models.IntegerField()),
                ('equipment_doi', models.CharField(max_length=255)),
                ('equipment_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_id', models.IntegerField()),
                ('notification_text', models.CharField(max_length=255)),
                ('notification_date', models.CharField(max_length=225)),
                ('notification_time', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('service_date', models.CharField(max_length=225)),
                ('service_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Complete'), ('3', 'shifted')], max_length=100)),
                ('service_remark', models.TextField()),
            ],
        ),
    ]
